name: CI/CD Build, Push, and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: testing/nrg-api-server
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t nrg-api-server:${{ env.IMAGE_TAG }} .
          docker save nrg-api-server:${{ env.IMAGE_TAG }} -o image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: image.tar

  push:
    name: Push Docker Image to Amazon ECR
    needs: build
    runs-on: ubuntu-latest

    outputs:
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: image-tar

      - name: Load Docker image
        run: |
          docker load -i image.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push to ECR
        run: |
          ECR_REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          IMAGE_URI="$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          docker tag nrg-api-server:${{ env.IMAGE_TAG }} $IMAGE_URI
          docker push $IMAGE_URI

  deploy:
    name: Deploy to API Server via Bastion
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        run: |
          echo "${{ secrets.BASTION_KEY }}" > bastion.pem
          chmod 600 bastion.pem

      - name: SSH into Bastion and Deploy
        run: |
          ECR_REGISTRY="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
          IMAGE_URI="$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"

          ssh -i bastion.pem -o StrictHostKeyChecking=no ${{ secrets.BASTION_USER }}@175.41.179.252 << EOF
            ssh -o StrictHostKeyChecking=no 10.0.131.122 << INNER
              echo "Logging into ECR..."
              aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REGISTRY

              echo "Pulling and running Docker image..."
              docker pull $IMAGE_URI
              docker stop nrg-api || true
              docker rm nrg-api || true
              docker run -d --name nrg-api -p 3000:3000 $IMAGE_URI
            INNER
          EOF
